// <auto-generated />
using System;
using EntropiaInventoryShareWeb.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EntropiaInventoryShareWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250809151713_AddExtraShareItemInfo")]
    partial class AddExtraShareItemInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EntropiaInventoryShareWeb.Entities.Avatar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastAccess")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("License")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LicenseExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Avatars");
                });

            modelBuilder.Entity("EntropiaInventoryShareWeb.Entities.InventorySharedItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AvatarId")
                        .HasColumnType("bigint");

                    b.Property<string>("Container")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtraData")
                        .HasColumnType("text");

                    b.Property<bool>("InAuction")
                        .HasColumnType("boolean");

                    b.Property<bool>("InShop")
                        .HasColumnType("boolean");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<double?>("MarkupAddToTT")
                        .HasColumnType("double precision");

                    b.Property<double?>("MarkupPercentage")
                        .HasColumnType("double precision");

                    b.Property<double?>("PerItemPrice")
                        .HasColumnType("double precision");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Shop")
                        .HasColumnType("text");

                    b.Property<int?>("TIR")
                        .HasColumnType("integer");

                    b.Property<double?>("Tier")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.HasIndex("ItemId");

                    b.ToTable("SharedItems");
                });

            modelBuilder.Entity("EntropiaInventoryShareWeb.Entities.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EntropiaNexusId")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<double?>("Value")
                        .HasColumnType("double precision");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("EntropiaInventoryShareWeb.Entities.InventorySharedItem", b =>
                {
                    b.HasOne("EntropiaInventoryShareWeb.Entities.Avatar", "Avatar")
                        .WithMany("SharedItems")
                        .HasForeignKey("AvatarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EntropiaInventoryShareWeb.Entities.Item", "Item")
                        .WithMany("SharedItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Avatar");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("EntropiaInventoryShareWeb.Entities.Avatar", b =>
                {
                    b.Navigation("SharedItems");
                });

            modelBuilder.Entity("EntropiaInventoryShareWeb.Entities.Item", b =>
                {
                    b.Navigation("SharedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
