services:
  db:
    image: postgres:16.9
    network_mode: "host"
    restart: always
    container_name: 'postgres-eis'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'eis'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
        PGPORT: 6432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data      
  entropiainventoryshareweb:
    image: ${DOCKER_REGISTRY-}entropiainventoryshareweb
    network_mode: "host"
    depends_on:
      - db
    # ports:
    #   - "5000:5000"
    build:
      context: .
      dockerfile: EntropiaInventoryShareWeb/Dockerfile
